# NumPy

[Documentation](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [1]:
import numpy as np

# Create a basic array

In [8]:
np.array([1, 2, 3])
np.zeros(2)
np.ones(2)
np.empty(2) 

array([1., 1.])

In [9]:
## You can create an array with a range of elements:
np.arange(4)
np.arange(2, 9, 2)

array([2, 4, 6, 8])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [10]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Specifying your data type

In [11]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example.ndim) # 3 d array
print(array_example.size) # total number of elements
print(array_example.shape) # shape

3
24
(3, 2, 4)


# Reshaping the array

In [17]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


# Convert a 1D array into a 2D array

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.shape)
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

x = np.expand_dims(col_vector, axis=2)
print(x.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
(6, 1, 1)
